create table
  public."Productos" (
    id_producto bigint generated by default as identity,
    nombre_producto text not null,
    id_marca integer not null,
    descripcion text not null,
    precio numeric not null,
    stock numeric not null,
    img_producto text not null,
    id_categoria integer not null,
    id_tipopc bigint null,
    constraint productos1_pkey primary key (id_producto),
    constraint Productos_id_tipopc_fkey foreign key (id_tipopc) references "TipoPC" (id_torre) on update cascade,
    constraint public_Productos_id_categoria_fkey foreign key (id_categoria) references "Categoria" (id_categoria) on update cascade,
    constraint public_productos_id_marca_fkey foreign key (id_marca) references "Marcas" (id_marca) on update cascade
  ) tablespace pg_default;

create table
  public."Marcas" (
    id_marca bigint generated by default as identity,
    nombre_marca character varying(255) not null default '255'::character varying,
    constraint marcas_pkey primary key (id_marca),
    constraint marcas_nombre_marca_key unique (nombre_marca)
  ) tablespace pg_default;

create table
  public."Categoria" (
    id_categoria integer generated by default as identity,
    nombre_categoria character varying not null,
    descripcion_categoria text not null,
    constraint Categoria_pkey primary key (id_categoria)
  ) tablespace pg_default;

create table
  public."TipoPC" (
    id_torre bigint generated by default as identity,
    tipo_torre text null,
    constraint TipoPC_pkey primary key (id_torre)
  ) tablespace pg_default;

create table
  public."Carrito" (
    id_carrito bigint generated by default as identity,
    userid uuid not null,
    id_producto bigint not null,
    cantidad integer not null default 1,
    constraint Carrito_pkey primary key (id_carrito),
    constraint carrito_user_id_fkey foreign key (userid) references auth.users (id) on update cascade,
    constraint public_Carrito_producto_id_fkey foreign key (id_producto) references "Productos" (id_producto) on update cascade
  ) tablespace pg_default;